//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurkishLanguageLibrary.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToWordNodesTest
    {
        public int Id { get; set; }
        public string Word { get; set; }
        public string ExpectedWord { get; set; }
        public string RootWord { get; set; }
    }
}
